In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
np.random.seed(42)
X = np.random.rand(100, 1) - 0.5
y = 3*X[:, 0]**2 + 0.05 * np.random.randn(100)

In [10]:
df = pd.DataFrame()
df['X'] = X.reshape(100)
df['y'] = y
df

           X         y
0  -0.125460  0.051573
1   0.450714  0.594480
2   0.231994  0.166052
3   0.098658 -0.070178
4  -0.343981  0.343986
..       ...       ...
95 -0.006204 -0.040675
96  0.022733 -0.002305
97 -0.072459  0.032809
98 -0.474581  0.689516
99 -0.392109  0.502607

[100 rows x 2 columns]

In [15]:
df['pred1'] = np.mean(df['y'])
df['res1'] = df['y']-df['pred1']

In [16]:
from sklearn.tree import DecisionTreeRegressor
dt1 = DecisionTreeRegressor(max_leaf_nodes=8)

In [25]:
dt1.fit(df['X'].values.reshape(100,1),df['res1'].values)
df['pred2'] = 0.265458 + 0.1*dt1.predict(df['X'].values.reshape(-1,1))

In [28]:
dt2 = DecisionTreeRegressor(max_leaf_nodes=8)
df['res2'] = df['y']-df['pred2']
dt2.fit(df['X'].values.reshape(100,1),df['res2'].values)
df['pred3'] = df['pred2'] + 0.1*dt2.predict(df['X'].values.reshape(-1,1))

In [29]:
df

           X         y     pred1      res1     pred2      res2     pred3
0  -0.125460  0.051573  0.265458 -0.213885  0.240744 -0.189171  0.217805
1   0.450714  0.594480  0.265458  0.329021  0.299501  0.294979  0.332056
2   0.231994  0.166052  0.265458 -0.099407  0.260491 -0.094439  0.256329
3   0.098658 -0.070178  0.265458 -0.335636  0.240744 -0.310922  0.217805
4  -0.343981  0.343986  0.265458  0.078528  0.269509  0.074477  0.273154
..       ...       ...       ...       ...       ...       ...       ...
95 -0.006204 -0.040675  0.265458 -0.306133  0.240744 -0.281419  0.217805
96  0.022733 -0.002305  0.265458 -0.267763  0.240744 -0.243049  0.217805
97 -0.072459  0.032809  0.265458 -0.232650  0.240744 -0.207936  0.217805
98 -0.474581  0.689516  0.265458  0.424057  0.305003  0.384512  0.341600
99 -0.392109  0.502607  0.265458  0.237148  0.287692  0.214915  0.308455

[100 rows x 7 columns]